### ISSUE TITLE
ImportError: No module named 'clustpipeline'

### ISSUE THREAD

**Issue by gufranca** [BaselAbujamous/clust#10]
Dear Basel,

Thanks a lot for providing Clust, I am really excited to use your tool, which looks amazing. I am having some problems to run it. I have all the dependencies satisfied and the installation was smooth. However, when try to run clust, I get the following error:

raceback (most recent call last):
  File "/home/gu/miniconda3/envs/work/bin/clust", line 7, in <module>
    from clust.__main__ import main
  File "/home/gu/miniconda3/envs/work/lib/python3.5/site-packages/clust/__main__.py", line 4, in <module>
    import clustpipeline
ImportError: No module named 'clustpipeline'

Do you have any idea on how to fix this?
I appreciate any help!
Thanks
Gustavo

**Comment by BaselAbujamous** [comment]
Hi Gustavo

Thanks for using Clust. It seems that you installed it using Python 3, didn't you? Clust is not yet compatible with Python 3, so if you install it using Python 2 it should work.

I am planning to make it compatible with Python 3 as soon as I can though.

Please let me know if this sorts the problem out.

Best wishes
Basel

**Comment by gufranca** [comment]
Hi Basel,

Thanks for the quick reply! Yes, I tried with Python 3 so I will try with Python 2 then.

Best wishes,
Gustavo

**Comment by BaselAbujamous** [comment]
Hi Gustavo

I hope trying Python 2 has fixed the issue. I will close this issue now and feel free to reopen it or to submit another issue if you need.

All the best!
Basel

**Comment by BaselAbujamous** [comment]
Hi Gustavo,

Update: Clust 1.10.0 now is compatible with Python 3 (as well as 2.7)!

All the best

**Comment by gufranca** [comment]
That's awesome! Thank you!
