### ISSUE TITLE
Output representative expression profiles of the clusters

### ISSUE THREAD

**Issue by apcamargo** [BaselAbujamous/clust#16]
Hi Basel,

In many cases, it's very useful to use a prototypical expression profile of the clusters in downstream analysis (by measuring it's correlation to an external variable, for instance). In WGCNA, the eigengene of the modules are usually used for this purpose.

It would be useful if Clust could output some kind of representation of the expression profile of each cluster. It could be the eigengene, median expression for each sample, trimmed mean etc.

What do you think?

**Comment by BaselAbujamous** [comment]
Hi Antoni,

I agree. I usually use mean expression. Data is all available in the output for people to generate this, but it would be nice to provide them with that ready in a separate TSV file. I will consider this in future versions. I will keep this issue open until then.

P.S. Thanks a lot for your recent edits (fixing requirements in README and changing transparency of the plots). I have merged them and they will be part of the next version of the pip-installed package. I liked the idea. Thanks for the contribution.

Basel

**Comment by apcamargo** [comment]
Do you think the mean expression in each condition is a good option? I imagine that there won't be many outlier values (as the expression needs to be at least similar to the cluster profile), but I feel that the average isn't robust enough.

Using trimmed means or medians seems better to me (I might be mistaken). I don't know if the eigengene is robost to ouliers, but I think we can investigate it.

(You're welcome! I really appreciate the effort you put into Clust and I'm willing to help you from a user perspective.)

**Comment by BaselAbujamous** [comment]
Maybe trimmed means makes sense. As the algorithm aims at taking out any outliers anyway, trimmed mean and normal mean would be similar. To be on the safe side, I would use the trimmed mean approach as you suggested.

Your help is much appreciated by ideas or even by direct edits, indeed.

**Comment by apcamargo** [comment]
It seems I was computing the eigengenes wrong after all. It looks like eigengenes are by far the best way to build a representative expression profile for the clusters.

[clust_test_representative_profiles_v2.pdf](https://github.com/BaselAbujamous/clust/files/2591427/clust_test_representative_profiles_v2.pdf)

(For some reason, the signs in the C2's eigengenes are opposed to what they should be. I don't know what is causing this. Do you have any idea?)

**Comment by apcamargo** [comment]
I did a Python implementation of the eigengene computation (and some plots comparing it to the medians, trimmed means and means).

[Python_eigengenes.pdf](https://github.com/BaselAbujamous/clust/files/2593532/Python_eigengenes.pdf)

**Comment by BaselAbujamous** [comment]
This is some great effort, Antônio! Thanks a lot!

I can see your point, and I believe I will incorporate that in the next version of Clust! I may test it over some other datasets as (with higher dimensions maybe).

Your input is much appreciated and will definately make using Clust a better experience for users!

Thanks again!
Basel

**Comment by BaselAbujamous** [comment]
Sorry for being late in responding. I am totally happy with it if you would like to work on a PR! Thanks.

**Comment by taylorreiter** [comment]
Hello! Will this be implemented in clust soon? I see #20, and am wondering if it is possible to have this functionality integrated.

**Comment by BaselAbujamous** [comment]
Sorry for the very late response here. I have just merged the edits by @apcamargo allowing for this capability. Thanks a lot, @apcamargo .

**Comment by apcamargo** [comment]
Thanks @BaselAbujamous!
