### ISSUE TITLE
does not work with missing genes

### ISSUE THREAD

**Issue by ChrisCarrie** [BaselAbujamous/clust#28]
Hi

So first this is really cool software. However I have noticed a problem when running with multiple species.
Basically if in the mapping folder there is any gene which does not have a corresponding gene in the other species clust just stops. I even tried just randomly deleting genes in the provided data and it still does not work. Is there a bug somewhere making this happen. When I change my mapping file and delete any genes which are not found in all species everything runs fine.

Thanks 
Chris

**Comment by BaselAbujamous** [comment]
Hi Chris

Thanks for seeing it as a cool software! And thanks for your question!

Sorry, I have just noticed that a previous question of yours has skipped my sight and I haven't responded to it yet.

Clust should be okay if some genes exist only in one species. Does your gene mapping file consider the correct format in these cases? for example, if gene1 and gene2 from the first species are orthologues of geneX from the second species, their line in the gene mapping file would be 

Gene_group_ID TAB gene1,gene2 TAB geneX

If gene3 in the first species has no orthologue in the second species, the gene mapping file's line would be:

Gene_group_ID TAB gene3 TAB

If geneY in the second species has no orthologue in the first species, the gene mapping file's line would be:

Gene_group_ID TAB TAB geneY

------

If the format of the gene mapping file is correct but the problem still exists, please let me know. Clust should be able to deal with this case without problems.

All the best
Basel

**Comment by ChrisCarrie** [comment]
Hi Basel

I get what you are saying. The file does appear t be formatted properly. I even just took your sample data and deleted one gene and it stops working. I checked the file and there is definitely the format 

genegroupid TAB TAB geneY

I even tried opening it in excel and resaving as both a csv or a tab delimited text. 

So must be an error somewhere

Cheers

Chris

**Comment by BaselAbujamous** [comment]
hmm shouldn't make a problem but will have a look. Thanks for reporting this bug, Chris :)

**Comment by BaselAbujamous** [comment]
Hi, I am closing this issue now as I think it has been resolved. Please feel free to reopen it or to submit any other issue that you face.

Best wishes
Basel
