### ISSUE TITLE
Custom normalisation methods

### ISSUE THREAD

**Issue by jianhaizhang** [BaselAbujamous/clust#33]
Hi, I didn't find the normalisation method I want to use. Is there a way I can apply my own normalisation code?

**Comment by BaselAbujamous** [comment]
Hi Jian,

Which normalisation method did you want to use?

Best,
Basel

**Comment by jianhaizhang** [comment]
Hi Basel,

I want to use the coefficient of variance and pOverA from the R package genefilter.

Regards,
