### ISSUE TITLE
Run command

### ISSUE THREAD

**Issue by jianhaizhang** [BaselAbujamous/clust#34]
In the example, there is a code of "clust Data/", shall it be executed in Python 2.7?

**Comment by BaselAbujamous** [comment]
Yes, it should be installed and then run in Python 2.7. I hope this sorts out your problem!

All the best,
Basel

**Comment by BaselAbujamous** [comment]
Dear Jian,

I will close this issue for now, but please feel free to reopen it if needed or to come back with any other issues.

Hint: I am planning to upgrade clust to run under Python 3 soon, but not yet.

All the best
Basel

**Comment by BaselAbujamous** [comment]
Hi Jian,

Update: Clust 1.10.0 now is compatible with Python 3 (as well as 2.7)!

All the best

**Comment by jianhaizhang** [comment]
Hi Basel,

Thanks for your update!

Regards,
Jianhai
