### ISSUE TITLE
cluster plots in PDF issue

### ISSUE THREAD

**Issue by Wen-Juan** [BaselAbujamous/clust#40]
Hi Basel,

For recent Clust plots I have done, the process was running successfully and all related results files are produced but the clusters plots in PDF is missing. I am wondering which particular required program/software for Clust I am missing? Thanks.

Here is a screenshot for the error message:

/===========================================================================\
|                                   Clust                                   |
|    (Optimised consensus clustering of multiple heterogenous datasets)     |
|           Python package version 1.10.0 (2018) Basel Abu-Jamous           |
+---------------------------------------------------------------------------+
| Analysis started at: Sunday 17 March 2019 (17:25:40)                      |
| 1. Reading dataset(s)                                                     |
| 2. Data pre-processing                                                    |
|  - Flat expression profiles filtered out (default in v1.7.0+).            |
|    To switch it off, use the --no-fil-flat option (not recommended).      |
|    Check https://github.com/BaselAbujamous/clust for details.             |
| 3. Seed clusters production (the Bi-CoPaM method)                         |
| 10%                                                                       |
| 20%                                                                       |
| 30%                                                                       |
| 40%                                                                       |
| 50%                                                                       |
| 60%                                                                       |
| 70%                                                                       |
| 80%                                                                       |
| 90%                                                                       |
| 100%                                                                      |
| 4. Cluster evaluation and selection (the M-N scatter plots technique)     |
| 10%                                                                       |
| 20%                                                                       |
| 30%                                                                       |
| 40%                                                                       |
| 50%                                                                       |
| 60%                                                                       |
| 70%                                                                       |
| 80%                                                                       |
| 90%                                                                       |
| 100%                                                                      |
| 5. Cluster optimisation and completion                                    |
| 6. Saving results in                                                      |
| Tv_output/                                                                |
| Error: could not save clusters plots in a PDF file.                       |
| Resuming producing the other results files ...                            |
+---------------------------------------------------------------------------+
| Analysis finished at: Sunday 17 March 2019 (17:37:43)                     |
| Total time consumed: 0 hours, 12 minutes, and 3 seconds                   |
|                                                                           |
\===========================================================================/

/===========================================================================\
|                              RESULTS SUMMARY                              |
+---------------------------------------------------------------------------+
| Clust received 2 datasets with 44635 unique genes. After filtering,       |
| 43671 genes made it to the clustering step. Clust generated 12 clusters   |
| of genes, which in total include 9213 genes. The smallest cluster         |
| includes 42 genes, the largest cluster includes 2163 genes, and the       |
| average cluster size is 768 genes.                                        |
+---------------------------------------------------------------------------+

Cheers,
Wen-Juan

**Comment by BaselAbujamous** [comment]
Hi Wen-Juan

Thanks for your question. Have you ever tried Clust on any other dataset(s) and got a PDF successfully? If yes, was in on the same system (computer/operating system/python)?

I have doubts in any possible memory requirements that have prevented generating the PDF for this study.

Will take it from there to help you in this problem

Best wishes
Basel

**Comment by Wen-Juan** [comment]
Hi Basel,

Yes, Clust can generate PDF in my laptop earlier when Clust was only compatible with Python version 2 (where I removed Python 3). Now Clust could not run in my laptop despite I reinstall python3, i do not know why.

Then I install the Clust on my iMac, it was running successfully but not generate PDF files. iMac and my Apple laptop has similar operating system but iMac was not with the most updated OS Mojave dark mode, my laptop is. iMac has python 3 not python2.

It should not be memory requirement. 

Cheers, 
Wen-Juan

**Comment by BaselAbujamous** [comment]
Hmm

The package that makes the PDF is matplotlib (which can be installed with pip). Do you have it installed with the same python version of clust itself? It should be automatically installed as clust is installed but sometimes versions clash with each other.

Clust should be fully installable with python 2 or python 3. You don't have to reinstall it with python 3 if you already have it installed with python 2.

Please let me know if this solves your problem.

Good luck!
Basel

**Comment by BaselAbujamous** [comment]
Sorry Wen-Juan, I have just found out that there is a problem in the plotting function! I am fixing it and will let you know when it is done! Today or tomorrow max should be all working well with version 1.10.1!

Thanks a lot for reporting this :)

**Comment by Wen-Juan** [comment]
ok, thanks :)

**Comment by BaselAbujamous** [comment]
Hi. I have just published a new release (clust v1.10.1) in which the PDF bug should be fixed. I would highly appreciate it if you reinstall clust with this new version and let me know if it fixes your problem.

Hint: you might need to use --upgrade and/or --no-cache-dir with pip install to force pip to fetch the most recent version rather than using the previous version from the cache.

Looking forward to hearing good news and thanks again for reporting this bug!

**Comment by Wen-Juan** [comment]
ok, many thanks. I will have a go and let you know how it goes.

**Comment by Wen-Juan** [comment]
hey!!!! It works now, and can generate the PDF files. You fix this issue :)

Many thanks!

**Comment by Wen-Juan** [comment]
I think you can close this issue now.

**Comment by BaselAbujamous** [comment]
Great news! I hope the clusters you get also make sense and are useful for your project :)

Please feel free to come back with any further issues/questions.

All the best
Basel

**Comment by taylorreiter** [comment]
I am getting this same error. I install clust with `conda install -c bioconda clust`, and I get pdf output for some count matrices I run clust on but not on others. I'm using clust version 1.10.7 and matplotlib 2.2.3.

**Comment by margaridamccferreira** [comment]
Hi Basel!

I also am getting the same error everytime I set `-t ` to any number different from 1. That is, I can only generate a .pdf output when the tightness parameter is the default 1. 

Thanks in advance!
Margarida

**Comment by dcowanturner** [comment]
Hi,  Basel.  
I'm getting the same error with Clust 1.10.7. and matplotlib 3.0.1. -  Tried updating matplotlib to 3.1.1 but no luck.    Worked well before using a different dataset -  might be an issue with the number of clusters its printing,  as it worked with below 10 clusters.    Cheers, Danny
