### ISSUE TITLE
Smaller and more clusters

### ISSUE THREAD

**Issue by jianhaizhang** [BaselAbujamous/clust#41]
Hi Basel,

I have the following questions:

1. I want to get smaller and more clusters on my single dataset. My command is "clust cor.os.txt -t 100 -o clust_result/ -n 0 --no-fil-flat -cs 10 
-K 40 42 44 46 50 52 54 56 58 60". I have pre-processed my data, so no pre-processing at all is needed when run clust. Is there an up limitation on "-t"? Can I set it as large as I want?

2. By using the above command, only half of the total genes were included in the final clusters. How to increase the number of genes in the final clusters?

Regards,
Jianhai

**Comment by BaselAbujamous** [comment]
Hi Jianhai

Thanks for your question.

1. There is no limit on -t but it will really saturate so "very large values" will not be different from "very very large values".

2. Clust doesn't directly control how many genes to be included in the final clusters; rather clust fills up the extracted clusters with genes as per the requested tightness. I haven't tried all possibilities for -K values, but how about using a wider and larger range? Probably -K 10 20 40 60 80 100 for example?

It is very interesting to see how these explorations go :)

All the best,
Basel
