### ISSUE TITLE
Proteomics

### ISSUE THREAD

**Issue by apmagalhaes** [BaselAbujamous/clust#5]
Do you have an idea if this method would work with proteomics data?

**Comment by BaselAbujamous** [comment]
In theory, it works. In practice, I have never tried it but I have always been keen to try it. Please go ahead and try it! I will be keen to hear your feedback.

Note: for normalisation, treat it as gene expression data. You may check the README page at https://github.com/BaselAbujamous/clust#normalisation. If unsure, please feel free to ask me by describing the format of your proteomic data.

BW 👍

**Comment by BaselAbujamous** [comment]
Hi apmagalhaes

I hope that you have been able to apply clust to your proteomics data successfully. I will close this "issue" as it is very old. Please feel free to come back to me with with any other issues.

All the best
Basel
