### ISSUE TITLE
Unrecognised replicate name (sMEPI_rep1) in line 1 in replicates

### ISSUE THREAD

**Issue by Zefeng-Wu** [BaselAbujamous/clust#53]
It exits after showing an error with "Unrecognised replicate name (sMEPI_rep1) in line 1 in replicates" when given the replicate file. Here are my commands and the replicate file.

clust sub_data.txt -r replicates  -o Clust_out -np 18
###########################################################
sub_data.txt	sMEPI	sMEPI_rep1,sMEPI_rep2,sMEPI_rep3
sub_data.txt	sMCOR	sMCOR_rep1,sMCOR_rep2,sMCOR_rep3
sub_data.txt	sMEND	sMEND_rep1,sMEND_rep2,sMEND_rep3
sub_data.txt	sMSTE	sMSTE_rep1,sMSTE_rep2,sMSTE_rep3
sub_data.txt	s0.5EPI	s0.5EPI_rep1,s0.5EPI_rep2,s0.5EPI_rep3
sub_data.txt	s0.5COR	s0.5COR_rep1,s0.5COR_rep2,s0.5COR_rep3
sub_data.txt	s0.5END	s0.5END_rep1,s0.5END_rep2,s0.5END_rep3
sub_data.txt	s0.5STE	s0.5STE_rep1,s0.5STE_rep2,s0.5STE_rep3
sub_data.txt	s6EPI	s6EPI_rep1,s6EPI_rep2,s6EPI_rep3
sub_data.txt	s6COR	s6COR_rep1,s6COR_rep2,s6COR_rep3
sub_data.txt	s6END	s6END_rep1,s6END_rep2,s6END_rep3
sub_data.txt	s6STE	s6STE_rep1,s6STE_rep2,s6STE_rep3
sub_data.txt	s24EPI	s24EPI_rep1,s24EPI_rep2,s24EPI_rep3
sub_data.txt	s24COR	s24COR_rep1,s24COR_rep2,s24COR_rep3
sub_data.txt	s24END	s24END_rep1,s24END_rep2,s24END_rep3
sub_data.txt	s24STE	s24STE_rep1,s24STE_rep2,s24STE_rep3

**Comment by BaselAbujamous** [comment]
Hi Zefeng,

Thanks for using Clust and for your question. Is this a name of a column in your data file "sub_data.txt"? Could provide the first line of this data file please? That can let me help you better :)

All the best
Basel
