### ISSUE TITLE
NameError: name 'Ds' is not defined

### ISSUE THREAD

**Issue by dsjones552** [BaselAbujamous/clust#54]
Hi,

Im getting this error while running Clust through miniconda on my Macbook pro. See code attached. Extremely new to Python, so fully expect I did something wrong getting this job submitted and/or Clust installed. Thanks for any help!

Daniel

[Clust_error.txt](https://github.com/BaselAbujamous/clust/files/4531643/Clust_error.txt)

**Comment by aliceb5** [comment]
Hi there,

Could you share how you fixed this? I'm getting this error whenever I change the -d setting.

Thank you,
Alice

**Comment by dsjones552** [comment]
Alice,

I actually never got it fixed. I switched to a different program in R

Good luck with it though!
Daniel

**Comment by aliceb5** [comment]
I think I've figured it out. The -d setting seems to refers to the number of count matrices. So, in the example data with three datasets, you can only set it as high as 3. 

I was (wrongly) thinking that this referred to samples (in my case, Illumina libraries)... and so I had set it at a number that was impossibly high. Hence getting an error that there are an improper number of D's!

Hopefully that helps someone else.

Alice
