### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by Hamsini-Ray** [BaselAbujamous/clust#59]
Hi Basel,

Thank you for making Clust. I am trying to use it for analyzing five species and a memory error came up. There seems to be a problem running it with the default number of datasets from which a gene needs to be included. The error log is attached. I would appreciate your help in solving this. Please note that everything went fine when I ran clust by specifying the number of datasets (clust Data/ -n 0 -m MapIDs.tsv -d 5).
[Error.txt](https://github.com/BaselAbujamous/clust/files/5218099/Error.txt)

Best regards,
Ray

**Comment by BaselAbujamous** [comment]
Happy to see this closed. I hope it has been resolved, @Hamsini-Ray ! Please let me know if further help is required. 👍
