### ISSUE TITLE
gene expression values in vertical axis

### ISSUE THREAD

**Issue by bioinfo17** [BaselAbujamous/clust#7]
Would be good if the expression values can be made visible in the vertical axis (at least 0 on the axis and the minimum and maximum values)? 

Thanks

**Comment by BaselAbujamous** [comment]
An important suggestion. I am planning to give users an easy control on how the plots are formatted by altering some parameters. This will be soon, but not this week. However, if it's an urgent request of yours (e.g. figure for a publication or a presentation), I am happy to help in producing your plots as you like.

**Comment by BaselAbujamous** [comment]
Dear bioinfo17

I have just released a new version (1.8.2) in which the expression values are visible in the vertical axis.

All the best

**Comment by BaselAbujamous** [comment]
Dear bioinfo17

I hope that my last response above was sufficient to address your request. I will close this issue now but please feel free to come to be on it or on any other issue.

Best wishes
